aliases:
 - &filter-only-master
   branches:
     only:
       - master

version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:12.10.0

    steps:
      - add_ssh_keys:
          fingerprints:
            - "3a:4a:09:a1:7e:64:aa:13:cc:31:3e:c9:51:46:c7:ed"
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "jceipek@users.noreply.github.com"
            git config --global user.name "Julian Ceipek"
            cd website && yarn install && GIT_USER=jceipek USE_SSH=true CUSTOM_COMMIT_MESSAGE="[skip ci] Automated Deploy via CircleCI" yarn run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
         # Only run on direct commits to master
         filters: *filter-only-master